<?php

namespace ContainerElDrnp3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Mwy7ciVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Mwy7ciV' shared service.
     *
     * @return \App\Repository\ChatMessageRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ChatController::fetchChatMessages()": the $chatMessageRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\ChatMessageRepository".');
    }
}
