<?php

namespace ContainerElDrnp3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0UTzXbZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0UTzXbZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0UTzXbZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminSecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\ChatController::fetchChatMessages' => ['privates', '.service_locator.9MwoPxv', 'get_ServiceLocator_9MwoPxvService', true],
            'App\\Controller\\ChatController::publish' => ['privates', '.service_locator.2LF_KP_', 'get_ServiceLocator_2LFKPService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UtilisateurController::admindhashboard' => ['privates', '.service_locator.4TftXj6', 'get_ServiceLocator_4TftXj6Service', true],
            'App\\Controller\\UtilisateurController::admindsettings' => ['privates', '.service_locator.a_b_a4I', 'get_ServiceLocator_ABA4IService', true],
            'App\\Controller\\UtilisateurController::changePassword' => ['privates', '.service_locator.riGN6sa', 'get_ServiceLocator_RiGN6saService', true],
            'App\\Controller\\UtilisateurController::deleteUser' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\UtilisateurController::editUser' => ['privates', '.service_locator.TIGO.0m', 'get_ServiceLocator_TIGO_0mService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AdminSecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\ChatController:fetchChatMessages' => ['privates', '.service_locator.9MwoPxv', 'get_ServiceLocator_9MwoPxvService', true],
            'App\\Controller\\ChatController:publish' => ['privates', '.service_locator.2LF_KP_', 'get_ServiceLocator_2LFKPService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UtilisateurController:admindhashboard' => ['privates', '.service_locator.4TftXj6', 'get_ServiceLocator_4TftXj6Service', true],
            'App\\Controller\\UtilisateurController:admindsettings' => ['privates', '.service_locator.a_b_a4I', 'get_ServiceLocator_ABA4IService', true],
            'App\\Controller\\UtilisateurController:changePassword' => ['privates', '.service_locator.riGN6sa', 'get_ServiceLocator_RiGN6saService', true],
            'App\\Controller\\UtilisateurController:deleteUser' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\UtilisateurController:editUser' => ['privates', '.service_locator.TIGO.0m', 'get_ServiceLocator_TIGO_0mService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AdminSecurityController::login' => '?',
            'App\\Controller\\ChatController::fetchChatMessages' => '?',
            'App\\Controller\\ChatController::publish' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UtilisateurController::admindhashboard' => '?',
            'App\\Controller\\UtilisateurController::admindsettings' => '?',
            'App\\Controller\\UtilisateurController::changePassword' => '?',
            'App\\Controller\\UtilisateurController::deleteUser' => '?',
            'App\\Controller\\UtilisateurController::editUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminSecurityController:login' => '?',
            'App\\Controller\\ChatController:fetchChatMessages' => '?',
            'App\\Controller\\ChatController:publish' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UtilisateurController:admindhashboard' => '?',
            'App\\Controller\\UtilisateurController:admindsettings' => '?',
            'App\\Controller\\UtilisateurController:changePassword' => '?',
            'App\\Controller\\UtilisateurController:deleteUser' => '?',
            'App\\Controller\\UtilisateurController:editUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
