<?php

namespace ContainerElDrnp3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9MwoPxvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9MwoPxv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9MwoPxv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chatMessageRepository' => ['privates', '.errored.Mwy7ciV', NULL, 'Cannot determine controller argument for "App\\Controller\\ChatController::fetchChatMessages()": the $chatMessageRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\ChatMessageRepository".'],
        ], [
            'chatMessageRepository' => '?',
        ]);
    }
}
