<?php

namespace ContainerElDrnp3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Symfony\Bundle\SecurityBundle\Security' shared autowired service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Symfony\\Bundle\\SecurityBundle\\Security'] = new \Symfony\Bundle\SecurityBundle\Security();
    }
}
