<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBsMbvOc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBsMbvOc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBsMbvOc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBsMbvOc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBsMbvOc\App_KernelDevDebugContainer([
    'container.build_hash' => 'BsMbvOc',
    'container.build_id' => '37b850c4',
    'container.build_time' => 1714642158,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBsMbvOc');
